# Generated by Django 4.2.4 on 2023-08-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_datacontributors_contributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataContributors',
        ),
    ]
