# Generated by Django 4.2.4 on 2023-08-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataContributors',
        ),
    ]
