# Generated by Django 4.2.4 on 2023-08-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataContrib',
        ),
    ]
