# Generated by Django 4.2.4 on 2023-08-03 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_auth', '0007_remove_almanachcontributor_first_name_and_more'),
        ('web', '0009_delete_datacontrib'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataContrib',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('unique_username', models.CharField(max_length=20)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
