# Generated by Django 4.2.4 on 2023-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_tipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipmodel',
            name='title',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
