# Generated by Django 4.2.4 on 2023-08-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanachcontributor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='almanachcontributor',
            name='second_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='almanachcontributor',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
