# Generated by Django 4.2.4 on 2023-08-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0002_almanachcontributor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanachcontributor',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='almanachcontributor',
            name='second_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='almanachcontributor',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
