# Generated by Django 4.2.4 on 2023-08-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0003_alter_almanachcontributor_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almanachcontributor',
            old_name='username',
            new_name='username_optional',
        ),
    ]
