# Generated by Django 4.2.4 on 2023-08-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0004_rename_username_almanachcontributor_username_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almanachcontributor',
            old_name='username_optional',
            new_name='your_username',
        ),
    ]
