# Generated by Django 4.2.4 on 2023-08-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0005_rename_username_optional_almanachcontributor_your_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almanachcontributor',
            old_name='your_username',
            new_name='unique_username',
        ),
    ]
