# Generated by Django 4.2.4 on 2023-08-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0006_rename_your_username_almanachcontributor_unique_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almanachcontributor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='almanachcontributor',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='almanachcontributor',
            name='unique_username',
        ),
    ]
