# Generated by Django 4.2.4 on 2023-08-03 11:29

import cooking_almanach.accounts_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0007_remove_almanachcontributor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='almanachcontributor',
            managers=[
                ('objects', cooking_almanach.accounts_auth.models.AlmanachContributorManager()),
            ],
        ),
        migrations.AddField(
            model_name='almanachcontributor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
