# Generated by Django 4.2.4 on 2023-08-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=30)),
                ('recipe_image', models.ImageField(upload_to='')),
                ('ingredients', models.CharField(max_length=250)),
                ('cooking_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('type_of_meal', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free'), ('Meat', 'Meat')], max_length=30)),
            ],
        ),
    ]
