# Generated by Django 4.2.4 on 2023-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='type_of_meal',
            field=models.CharField(max_length=30),
        ),
    ]
