# Generated by Django 4.2.4 on 2023-08-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipemodel_type_of_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='type_of_meal',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free'), ('Meat', 'Meat')], max_length=30),
        ),
    ]
