# Generated by Django 4.2.4 on 2023-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemodel_type_of_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
