# Generated by Django 4.2.4 on 2023-08-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
