# Generated by Django 4.2.4 on 2023-08-06 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_tipmodel_title'),
        ('recipes', '0017_comment_poster_two_alter_comment_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='user_unique_name',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='web.datacontrib'),
            preserve_default=False,
        ),
    ]
