# Generated by Django 4.2.4 on 2023-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipemodel_user_recipemodel_user_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe_title',
            field=models.CharField(max_length=100),
        ),
    ]
