# Generated by Django 4.2.4 on 2023-08-10 23:45

import cooking_almanach.recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipemodel_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.IntegerField(validators=[cooking_almanach.recipes.validators.time_too_long]),
        ),
    ]
