# Generated by Django 4.2.4 on 2023-08-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipemodel_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='type_of_meal',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free'), ('Meat', 'Meat'), ('Other', 'Other')], max_length=30),
        ),
    ]
