# Generated by Django 4.2.4 on 2023-08-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipemodel_type_of_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='recipe_image',
        ),
    ]
